#!/bin/sh

set -eu

root=$(realpath $(dirname "$0")/..)

generate() {
    local name input_path output_path

    name=$1

    input_path=$root/misc_html/$name.html.erb
    output_path=$root/misc_html/$name.html

    echo "generating $output_path"
    $root/misc_html/generate_html $input_path > $output_path
}

generate 404
generate 503
